/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.nus.iss.pos.gui;

import edu.nus.iss.pos.core.Category;
import edu.nus.iss.pos.core.Vendor;
import edu.nus.iss.pos.core.services.IInventoryService;
import edu.nus.iss.pos.dao.repositories.UnitOfWork;
import edu.nus.iss.pos.services.InventoryService;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Liu Zhenchang
 */
public class VendorReport extends CustomedFrame {
    
    VendorTableModel model = null;
    
    /**
     * Creates new form VendorReport
     * @param inventoryService
     */
    public VendorReport(IInventoryService inventoryService) {
        super();
        List<Vendor> vendors = null;
        try {
            vendors = inventoryService.getAllVendors();
        } catch (Exception ex) {
            Logger.getLogger(VendorReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        model = new VendorTableModel(vendors);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Vendor Report");

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class VendorTableModel extends AbstractTableModel {
        
        private List<Vendor> vendors = null;
        private final String[] columns = {"Vendor name", "Description", "Category"};
        
        public VendorTableModel(List<Vendor> vendors){
            super();
            this.vendors = vendors;
        }
        
        @Override
        public String getColumnName(int column) {
            return columns[column];
        }
        
        @Override
        public int getRowCount() {
            return vendors.size();
        }

        @Override
        public int getColumnCount() {
            return columns.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Vendor vendor = vendors.get(rowIndex);
                for(Category c : vendor.getCategories()) {
                }
            switch(columnIndex){
                case 0:
                    return vendor.getKey();
                case 1:
                    return vendor.getDescription();
                default:
                    String categories = "";
                    for(Category c : vendor.getCategories()) {
                        categories += c.getKey();
                    }
                    return categories;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
